# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default   # your self-hosted agent pool

steps:
- task: Maven@3
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\jdk-11.0.30'
    mavenVersionOption: 'Default'

# 👇 Publish the JAR file
- task: PublishBuildArtifacts@1
  displayName: 'Publish JAR Artifact'
  inputs:
    PathtoPublish: 'server/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'